#pragma once
#include "Window.h"
#include "GL/glew.h"
#include "GLFW/glfw3.h"
#include <iostream>
#include "Triangle.h"
#include "Manager.h"
#include "Quad.h"
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>